version: '3.8'

services:
  <%= projectName %>:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    networks:
      - <%= projectName %>-network

  # Add more services as needed (database, redis, etc.)
  # mongodb:
  #   image: mongo:6-jammy
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - <%= projectName %>-network

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - <%= projectName %>-network

networks:
  <%= projectName %>-network:
    driver: bridge

# volumes:
#   mongodb_data:
